DROP TRIGGER my_trigger;
DROP TRIGGER IF EXISTS my_trigger;
DROP TRIGGER mydb.my_trigger;
DROP TABLE users;
DROP TABLE IF EXISTS users;
DROP TABLE users, orders;
DROP TABLE IF EXISTS users, orders;
DROP DATABASE mydb;
DROP DATABASE IF EXISTS mydb;
DROP SCHEMA myschema;
DROP SCHEMA IF EXISTS myschema;
DROP VIEW myview;
DROP VIEW IF EXISTS myview;
DROP VIEW myview, otherview;
DROP INDEX idx_name ON users;
