GRANT SELECT ON mydb.* TO user1;
GRANT SELECT, INSERT ON mydb.* TO user1;
GRANT SELECT ON mydb.* TO user1@localhost;
GRANT SELECT ON mydb.* TO user1 WITH GRANT OPTION;
GRANT SELECT (id, name) ON mydb.users TO user1;
GRANT SELECT ON TABLE mydb.users TO user1;
GRANT SELECT ON mydb.users TO 'user1'@'localhost', 'user2'@'%';
GRANT ALL ON mydb.* TO user1;
GRANT EXECUTE ON PROCEDURE mydb.myproc TO user1;
GRANT EXECUTE ON FUNCTION mydb.myfunc TO user1;
GRANT PROXY ON 'user1'@'localhost' TO 'user2'@'localhost';
GRANT role1 TO user1;
GRANT role1, role2 TO user1, user2;
GRANT SELECT ON *.* TO user1;
