INSERT INTO users VALUES (1, "John");
INSERT INTO users (id, name) VALUES (1, "John") ON DUPLICATE KEY UPDATE name = "Jane";
INSERT INTO users SET name = "John", email = "john@example.com";
INSERT IGNORE INTO users (name) VALUES ("John");
INSERT INTO t PARTITION (p0) VALUES (1);
INSERT INTO users (id) VALUES (1);
INSERT INTO db.users (id) VALUES (1);
INSERT INTO users (id, name, email) VALUES (1, "John", "john@example.com");
INSERT INTO users (id) VALUES (1), (2), (3);
INSERT INTO users (id, name) SELECT id, name FROM temp_users;
INSERT INTO users SET id = 1, name = "John", email = "john@example.com";
INSERT INTO users PARTITION (p0, p1) (id) VALUES (1);
INSERT users (id) VALUES (1);
INSERT IGNORE users (id) VALUES (1);
INSERT IGNORE INTO users (id) VALUES (1);
INSERT INTO users SET name = "John", age = 30;
INSERT INTO users (name, age) VALUES ("John", 30);
INSERT INTO users (name, age) SELECT name, age FROM temp_users;
INSERT INTO users (id, name) VALUES (1, 'John');
INSERT INTO users VALUES (1, 'John');
