SELECT id, ROW_NUMBER() OVER w FROM t WINDOW w AS (ORDER BY id);
SELECT ROW_NUMBER() OVER w FROM t WINDOW w AS (ORDER BY id);
SELECT * FROM (t1, t2);
SELECT 1 UNION SELECT 2;
SELECT COUNT(*) FROM users;
SELECT COUNT(user_id) FROM orders;
SELECT COUNT(*) FROM orders;
SELECT COUNT(DISTINCT user_id) FROM orders;
SELECT GROUP_CONCAT(name ORDER BY name ASC) FROM users;
SELECT GROUP_CONCAT(name) FROM users;
SELECT SUM(amount) OVER (PARTITION BY user_id) FROM orders;
SELECT GROUP_CONCAT(name SEPARATOR ', ') FROM users;
SELECT GROUP_CONCAT(DISTINCT name ORDER BY name DESC SEPARATOR '|') OVER (PARTITION BY category) FROM products;
SELECT GROUP_CONCAT(DISTINCT name ORDER BY name SEPARATOR ', ') FROM users;
SELECT COUNT(id) FROM users;
SELECT COUNT(DISTINCT id) FROM users;
SELECT GROUP_CONCAT(name ORDER BY name) FROM users;
SELECT * FROM t WHERE a AND b;
SELECT * FROM t WHERE a OR b;
SELECT * FROM t WHERE age > 18;
SELECT * FROM t WHERE age BETWEEN 18 AND 65;
SELECT * FROM t WHERE name IS NULL;
SELECT * FROM t WHERE name IS NOT NULL;
SELECT * FROM t WHERE NOT active;
SELECT * FROM t WHERE id IN (1, 2, 3);
SELECT CONCAT(first_name, ' ', last_name) FROM users;
SELECT * FROM t WHERE (a AND b) OR c;
SELECT * FROM t WHERE EXISTS (SELECT 1 FROM users);
SELECT * FROM users ORDER BY name ASC;
SELECT * FROM users ORDER BY name DESC;
SELECT * FROM users ORDER BY name;
SELECT * FROM users LIMIT 10;
SELECT * FROM users LIMIT 10, 20;
SELECT COUNT(*) FROM users GROUP BY status;
SELECT COUNT(*) as cnt FROM users GROUP BY status HAVING cnt > 5;
SELECT id FROM users;
SELECT id AS user_id FROM users;
SELECT * FROM users;
SELECT * FROM users LIMIT 10 OFFSET 20;
SELECT * FROM users LIMIT 20, 10;
SELECT CASE WHEN age < 13 THEN "child" WHEN age < 18 THEN "teen" WHEN age < 65 THEN "adult" ELSE "senior" END FROM users;
SELECT id INTO @var FROM t;
SELECT COUNT(*) FROM t GROUP BY id HAVING COUNT(*) > 1;
SELECT COUNT(*) FROM t GROUP BY id WITH ROLLUP;
SELECT DATE_ADD('2020-01-01', INTERVAL 1 DAY);
SELECT * FROM t WHERE id = :id;
SELECT * FROM t;
SELECT 'hello';
SELECT 42;
SELECT TRUE;
SELECT NULL;
SELECT UPPER(name) FROM users;
SELECT CASE WHEN age > 18 THEN "adult" ELSE "minor" END FROM users;
SELECT CAST(id AS VARCHAR) FROM users;
SELECT * FROM users AS u;
SELECT * FROM users JOIN orders ON users.id = orders.user_id;
SELECT 1 FROM DUAL;
SELECT NOW() FROM DUAL;
SELECT * FROM mydb.users;
SELECT * FROM users INNER JOIN orders ON users.id = orders.user_id;
SELECT * FROM users INNER JOIN orders USING (user_id);
SELECT * FROM (SELECT id FROM users) AS sub;
SELECT * FROM (SELECT id FROM users);
SELECT 1;
SELECT mydb.UPPER(name) FROM users;
SELECT JSON_EXTRACT(data, "$.name") FROM users;
SELECT CONCAT(first, last) FROM users;
SELECT NOW() FROM dual;
SELECT ROW_NUMBER() OVER (ORDER BY id) FROM users;
SELECT ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary) FROM employees;
SELECT CURRENT_TIMESTAMP() FROM dual;
SELECT CURRENT_TIMESTAMP;
SELECT * FROM users LEFT JOIN orders ON users.id = orders.user_id;
SELECT * FROM users RIGHT JOIN orders ON users.id = orders.user_id;
SELECT * FROM t WHERE name LIKE "test%";
SELECT * FROM t WHERE name LIKE "test\\\\%" ESCAPE "\\\\";
SELECT * FROM t WHERE name NOT LIKE "test%";
SELECT * FROM t WHERE name LIKE 'test%';
SELECT SUM(amount) OVER (PARTITION BY category, region ORDER BY date) FROM sales;
SELECT (id) AS user_id FROM users;
SELECT mydb.myfunc(id) FROM users;
SELECT * FROM users COLLATE utf8_general_ci;
SELECT id, COUNT(*) FROM users GROUP BY id;
SELECT id, COUNT(*) FROM users GROUP BY id WITH ROLLUP;
SELECT dept, year, COUNT(*) FROM employees GROUP BY dept, year;
SELECT id INTO @var FROM users;
SELECT id FROM users INTO OUTFILE "/tmp/data.txt";
SELECT id FROM users WHERE active = 1 INTO @var;
SELECT 1, 1e1, TRUE, FALSE, 1.1, NULL, "foo", 'bar', `baz`;
WITH cte AS (SELECT id FROM users) SELECT * FROM cte;
SELECT SQL_CALC_FOUND_ROWS * FROM users;
SELECT SQL_CACHE * FROM users;
SELECT SQL_NO_CACHE * FROM users;
SELECT DISTINCT name FROM users;
SELECT * FROM (SELECT id FROM users) AS t;
SELECT * FROM (users, orders);
SELECT * FROM users WHERE id = 1;
SELECT * FROM users WHERE NOT active;
SELECT * FROM users WHERE ISNULL(name);
SELECT dept, COUNT(*) FROM users GROUP BY dept HAVING COUNT(*) > 5;
SELECT id FROM users UNION SELECT id FROM admins;
SELECT id FROM users UNION ALL SELECT id FROM admins;
SELECT * FROM (SELECT * FROM users) AS t;
SELECT * FROM users FOR UPDATE;
SELECT * FROM users LOCK IN SHARE MODE;
SELECT * FROM users FOR UPDATE NOWAIT;
SELECT * FROM users FOR UPDATE SKIP LOCKED;
SELECT * FROM users FOR UPDATE WAIT 5;
SELECT * FROM users for update wait 5;
SELECT id, name FROM users;
SELECT id, (SELECT name FROM users WHERE users.id = t.user_id) as user_name FROM t;
SELECT id, (SELECT name FROM users) as user_name FROM t;
SELECT (SELECT COUNT(*) FROM orders WHERE orders.user_id = u.id) as order_count, (SELECT MAX(created_at) FROM orders WHERE orders.user_id = u.id) as last_order FROM users u;
SELECT * FROM users WHERE id IN (SELECT user_id FROM orders);
SELECT id, (SELECT COUNT(*) FROM orders WHERE user_id = users.id) AS order_count FROM users;
SELECT * FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE user_id = users.id);
SELECT (SELECT id FROM users) AS user_id;
SELECT * FROM users WHERE (id, name) IN (SELECT user_id, user_name FROM orders);
SELECT (SELECT u.id FROM users u JOIN orders o ON u.id = o.user_id) AS data;
SELECT 42 FROM dual;
SELECT TRUE FROM dual;
SELECT * FROM users ORDER BY id + 1 DESC;
SELECT 'hello' FROM dual;
SELECT id FROM users UNION SELECT id FROM customers;
SELECT id FROM users UNION ALL SELECT id FROM customers;
SELECT id FROM users UNION DISTINCT SELECT id FROM customers;
SELECT id FROM users UNION SELECT id FROM customers UNION SELECT id FROM vendors;
SELECT DATE_ADD(NOW(), INTERVAL 1 DAY);
SELECT * FROM users WHERE id = :id;
SELECT @myvar;
SELECT FALSE;
SELECT "hello";
SELECT `hello`;
SELECT :param;
SELECT X'4D7953514C';
SELECT B'1010';
SELECT DATE '2023-01-01';
SELECT TIMESTAMP '2023-01-01 12:00:00';
SELECT TIME '12:00:00';
SELECT N'hello';
SELECT SUM(amount) OVER (ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM orders;
SELECT SUM(amount) OVER (PARTITION BY user_id ORDER BY date) FROM orders;
SELECT SUM(amount) OVER w FROM orders WINDOW w AS (PARTITION BY user_id);
WITH cte (id, name) AS (SELECT id, name FROM users) SELECT * FROM cte;
WITH cte AS (SELECT id, name FROM users) SELECT * FROM cte;
WITH my_cte AS (SELECT 1) SELECT * FROM my_cte;
WITH cte (id, name) AS (SELECT 1, 2) SELECT * FROM cte;
WITH cte AS (SELECT 1, 2) SELECT * FROM cte;
WITH cte1 AS (SELECT 1), cte2 (x) AS (SELECT 2) SELECT * FROM cte1, cte2;
SELECT SQL_SMALL_RESULT * FROM users;
SELECT SQL_BIG_RESULT * FROM users;
SELECT SQL_BUFFER_RESULT * FROM users;
SELECT SUM(amount) OVER (ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM orders;
SELECT * FROM users CROSS JOIN orders;
SELECT id, name, age FROM users;
SELECT DISTINCT id, name FROM users;
SELECT id FROM users GROUP BY id, name;
SELECT * FROM users WHERE id BETWEEN 1 AND 100;
SELECT * FROM users WHERE name LIKE 'John%';
SELECT * FROM users WHERE id NOT IN (1, 2, 3);
SELECT * FROM users WHERE age >= 18 AND status = 'active';
SELECT COALESCE(name, 'Unknown') FROM users;
SELECT IFNULL(email, 'no-email') FROM users;
SELECT IF(age > 18, 'adult', 'minor') FROM users;
